
server:
  port: 9020

spring:
  application:
    name: appointment-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB