
/* department-service */

create table if not exists filial (
    id bigint generated by default as identity unique not null ,
    address varchar not null ,
    open time not null ,
    close time not null
);

create table if not exists department (
    id bigint generated by default as identity unique not null ,
    name varchar unique not null ,
    description text not null
);

create table if not exists filial_department (
    filial_id bigserial references filial(id) on DELETE cascade on UPDATE cascade ,
    department_id bigserial references department(id) on DELETE cascade on UPDATE cascade ,
    primary key (filial_id, department_id)
);

/* identity-service */

create table if not exists authority (
    id bigint generated by default as identity unique not null ,
    name varchar unique not null
);

create table if not exists identity (
    id bigint generated by default as identity unique not null ,
    email varchar unique not null ,
    phone varchar unique not null ,
    password varchar not null ,
    created timestamp not null ,
    authority_id bigint references authority(id)
        on DELETE set null on UPDATE cascade
);

/* employee-service */

create table if not exists position (
    id bigint generated by default as identity unique not null ,
    name varchar unique not null
);

create table  if not exists employee (
    id bigint generated by default as identity unique not null ,
    firstname varchar not null ,
    lastname varchar not null ,
    patronymic varchar not null ,
    gender varchar not null ,
    birthdate date not null ,
    about text not null ,
    identity_id bigint unique references identity(id)
        on DELETE cascade on UPDATE cascade ,
    filial_id bigint references filial(id)
        on DELETE set null on UPDATE cascade ,
    department_id bigint references department(id)
        on DELETE set null on UPDATE cascade
);

create table if not exists position_employee (
    position_id bigserial references position(id) on DELETE cascade on UPDATE cascade ,
    employee_id bigserial references employee(id) on DELETE cascade on UPDATE cascade ,
    primary key (position_id, employee_id)
);

/* patient-service */

create table if not exists patient (
    id bigint generated by default as identity unique not null ,
    firstname varchar not null ,
    lastname varchar not null ,
    patronymic varchar not null ,
    gender varchar not null ,
    birthdate date not null ,
    identity_id bigint unique references identity(id)
        on DELETE cascade on UPDATE cascade
);

/* appointment-service */

create table if not exists appointment (
    id bigint generated by default as identity unique not null ,
    firstname varchar not null ,
    lastname varchar not null ,
    patronymic varchar not null ,
    gender varchar not null ,
    description text ,
    date date not null ,
    hours time not null ,
    employee_id bigint references employee(id)
        on DELETE set null on UPDATE cascade ,
    patient_id bigint references patient(id)
        on DELETE set null on UPDATE cascade ,
    closed boolean not null
);

create table if not exists document (
    id bigint generated by default as identity unique not null ,
    filename varchar not null ,
    data bytea not null
);

create table if not exists conclusion (
    id bigint generated by default as identity unique not null ,
    appointment_id bigint unique references appointment(id)
        on DELETE set null on UPDATE cascade ,
    document_id bigint unique references document(id)
        on DELETE set null on UPDATE cascade
);

create table if not exists analysis (
    id bigint generated by default as identity unique not null ,
    patient_id bigint references patient(id) on DELETE set null on UPDATE cascade ,
    employee_id bigint references employee(id) on DELETE set null on UPDATE cascade ,
    document_id bigint unique references document(id)on DELETE set null on UPDATE cascade
);


/* ------------------------------------------------------ */


/* department-service population */

insert into filial(address, open, close) VALUES ('г. Новосибирск, Советский р-н, Иванова 45', '07:00','21:00');
insert into filial(address, open, close) VALUES ('г. Новосибирск, Железнодорожный р-н, Патрушева 14.2', '07:30','24:00');
insert into filial(address, open, close) VALUES ('г. Новосибирск, Калининский р-н, Рублева 110а', '08:00','21:00');

insert into department(name, description) VALUES ('Хирургия', 'Высококлассная Хирургия и все в таком духе');
insert into department(name, description) VALUES ('Терапия', 'Высококлассная Терапия и все в таком духе');
insert into department(name, description) VALUES ('Неврология', 'Высококлассная Неврология и все в таком духе');
insert into department(name, description) VALUES ('Урология', 'Высококлассная Урология и все в таком духе');
insert into department(name, description) VALUES ('Гастроэнтерология', 'Высококлассная Гастроэнтерология и все в таком духе');
insert into department(name, description) VALUES ('Диагностика', 'Высококлассная Диагностика и все в таком духе');
insert into department(name, description) VALUES ('Кардиология', 'Высококлассная Кардиология и все в таком духе');
insert into department(name, description) VALUES ('Лаборатория', 'Высококлассная Лаборатория для сдачи анализов');
insert into department(name, description) VALUES ('Стоматология', 'Высококлассная Стоматология и все в таком духе');
insert into department(name, description) VALUES ('Дерматология', 'Высококлассная Дерматология и все в таком духе');

insert into filial_department(filial_id, department_id) VALUES (1,1);
insert into filial_department(filial_id, department_id) VALUES (1,3);
insert into filial_department(filial_id, department_id) VALUES (1,4);
insert into filial_department(filial_id, department_id) VALUES (1,5);
insert into filial_department(filial_id, department_id) VALUES (1,7);
insert into filial_department(filial_id, department_id) VALUES (1,8);
insert into filial_department(filial_id, department_id) VALUES (1,9);

insert into filial_department(filial_id, department_id) VALUES (2,1);
insert into filial_department(filial_id, department_id) VALUES (2,2);
insert into filial_department(filial_id, department_id) VALUES (2,3);
insert into filial_department(filial_id, department_id) VALUES (2,4);
insert into filial_department(filial_id, department_id) VALUES (2,6);
insert into filial_department(filial_id, department_id) VALUES (2,7);
insert into filial_department(filial_id, department_id) VALUES (2,10);

insert into filial_department(filial_id, department_id) VALUES (3,2);
insert into filial_department(filial_id, department_id) VALUES (3,3);
insert into filial_department(filial_id, department_id) VALUES (3,4);
insert into filial_department(filial_id, department_id) VALUES (3,5);
insert into filial_department(filial_id, department_id) VALUES (3,6);
insert into filial_department(filial_id, department_id) VALUES (3,7);
insert into filial_department(filial_id, department_id) VALUES (3,8);
insert into filial_department(filial_id, department_id) VALUES (3,9);
insert into filial_department(filial_id, department_id) VALUES (3,10);

/* identity-service population */

insert into authority(name) values ('ADMIN');
insert into authority(name) values ('USER');
insert into authority(name) values ('EMPLOYEE');

insert into identity(email, phone, password, created, authority_id)
VALUES ('admin@gmail.com','+73832358956',
        '$2a$10$cuImZ95Nz47wEdtYRv2rUOdfIi0VBLF.WjZdQ6BrIsI1u.0V7SfDy','2020-01-01 21:00',1);
insert into identity(email, phone, password, created, authority_id)
VALUES ('doctor@gmail.com','+73833672514',
        '$2a$10$mLJxMIsfLROdzmLEngXY/.wgBQTTSroSHOAjUKDpsTo6MFKlyLp1S','2020-01-01 23:00',3);

insert into identity(email, phone, password, created, authority_id)
VALUES ('burgassme@gmail.com','+79139035373',
        '$2a$10$28Xt9mtrjsj2DsPlqqiWGeSdAbrw43gpeocTQDChwGal.K/abPpTW','2025-01-04 21:00',2);
insert into identity(email, phone, password, created, authority_id)
VALUES ('zagorulko@gmail.com','+77073574205',
        '$2a$10$N/nboOMNxvJYWLrDq/ZVt.g2mt.I47SNlEGl/KVc7ct97rFV/0rzG','2025-01-04 21:00',2);
insert into identity(email, phone, password, created, authority_id)
VALUES ('abdillaev@gmail.com','+79139815608',
        '$2a$10$R1UDw80w5rRdqU93T6JEDu8yTgk47K/G1ZLU66GlOr6fBbLDXoosi','2025-01-04 21:06',2);

/* employee-service population */

insert into position(name) VALUES ('Кардиолог');
insert into position(name) VALUES ('Гастроэнтеролог');
insert into position(name) VALUES ('Хирург');
insert into position(name) VALUES ('Терапевт');
insert into position(name) VALUES ('Невролог');
insert into position(name) VALUES ('Диагност');
insert into position(name) VALUES ('Стоматолог');
insert into position(name) VALUES ('Дерматолог');
insert into position(name) VALUES ('Врач высшей категории');
insert into position(name) VALUES ('к.м.н.');
insert into position(name) VALUES ('Уборщица');
insert into position(name) VALUES ('Эхокардиография');
insert into position(name) VALUES ('Врач ультразвуковой диагностики');

insert into employee(firstname, lastname, patronymic, gender, birthdate, about, identity_id, filial_id, department_id)
VALUES ('Катаев','Алексей','Игоревич','MALE','1985-04-23',
       'Об алексее Игоревиче кратко',2, 1, 2);

insert into position_employee(position_id, employee_id) VALUES (4,1);
insert into position_employee(position_id, employee_id) VALUES (9,1);
insert into position_employee(position_id, employee_id) VALUES (10,1);

/* patient-service population */

insert into patient(firstname, lastname, patronymic,  gender, birthdate, identity_id)
VALUES ('Burgas','Vyacheslav','Vasilich','MALE','1993-01-10',3);
insert into patient(firstname, lastname, patronymic, gender, birthdate,  identity_id)
VALUES ('Zagorulko','Boris','Urevich','MALE','1993-10-30',4);
insert into patient(firstname, lastname, patronymic, gender, birthdate, identity_id)
VALUES ('Abdillaev','Ruslan','Kujugetovich','MALE','1993-04-01',5);

/* appointment-service */

insert into appointment(firstname, lastname, patronymic, gender,  date, hours, employee_id, patient_id, closed)
VALUES ('Burgas','Vyacheslav','Vasilich','MALE','2024-07-15',
       '12:15', 1, 1, false);